printers:
  - address: <ip_address_of_printer>
    username: maker
    password: <password>
    name: <your_printer_name> # it's optional, only showed in Grafana dashboard
    type: MINI # MK35 / MK35S / MK39 / MK39S / MK4 / MK4S / XL / IX / Core One / Core One L